### ISSUE TITLE
I want a new function, just flip left and right, but top and down keep the same

### ISSUE THREAD

**Issue by jianyangusa** [ohmae/orientation-faker#17]
I have a wireless camera,  I put it in my vehicle as a rear mirror. But  the car on my left side, it shows on  the right side of the phone screen, while the car on my right side, it shows on the left side of the phone screen. I hope your application can help me.

**Comment by ohmae** [comment]
The ability to flip left and right is not in the Android system and cannot be achieved with this app. It is not the Android system that can fulfill your wish, but the camera app or the monitor app. Please make your request to that app.
