### ISSUE TITLE
Can we add these features as quick setting tiles?

### ISSUE THREAD

**Issue by Gideon-Felt** [ohmae/orientation-faker#19]
This app would be better used through the existing Android Quick settings tiles as opposed to a persistent notification.
Is this an option?

**Comment by ohmae** [comment]
This app requires a resident process
1. For that you need to show the sticky notification. There is no option to not show notifications.
2. Android tiles cannot fully reflect the state of such apps, so at most they can only launch apps.
In short, it's technically impossible.
