### ISSUE TITLE
Fdroid relase 

### ISSUE THREAD

**Issue by dostoievsky** [ohmae/orientation-faker#22]
I would like to know why this app was realased only in Play Store, mainterners didnt seen interest in releasing it on fdroid or similar "stores"?

**Comment by ohmae** [comment]
Because this app uses Google's libraries for crash investigation and monetization, it cannot be published on the G-Free store. I tried to publish this app on the Amazon store, but it didn't seem to meet their policies and was rejected.

**Comment by dostoievsky** [comment]
Hello ohmae, thank you for your reply. 
So, it cant be compiled manually also and inserted in a phone?
It must be installed with play store? 

Would you consider also, making a version without GAPPS and add some kind of donation section?

I would happly donate you for this app if it meets my requirements. I am currently using 
https://play.google.com/store/apps/details?id=org.crape.rotationcontrol on a waydroid running LineageOS on a PinePhone. I have installed rotation control with Aurora Store, and I think it is possible to install ours as well with this workflow, but I dont know if I will have issues because of missing GAPPS contents.

**Comment by dostoievsky** [comment]
Closing this issue since maintener gave his reasons and dosent show interest in continuing this thread. Thank you.
