### ISSUE TITLE
Please clarify on GMS/FCM

### ISSUE THREAD

**Issue by IzzySoft** [ohmae/orientation-faker#6]
Just being curious: what for does the app require GMS, Firebase and cloud messaging? The app description gives no clue for this. If it's not strictly needed, would you consider a build variant coming without those, and offering the resulting APK e.g. here via [releases](https://github.com/ohmae/orientation-faker/releases)? The "Google-free" folks certainly would appreciate it :smiley: I guess it would even be possible to not require any network permissions at all for managing screen orientation…

Thanks in advance!

**Comment by ohmae** [comment]
My main purpose of firebase and gms is

- Firebase Crashlytics for crash analysis
- AdMob for monetization

This app is also used for my various experiments.
For now, I'm not going to publish this app in a "Google-free" apk.
It does not mean that my intention will stay the same tomorrow :wink: 

Of course, this source code is released under the MIT license, so anyone can use it freely.

**Comment by IzzySoft** [comment]
Thanks for clarification, @ohmae! AdMob I meanwhile guessed, Crashlytics I somehow missed. Looking forward to the day you decide for a G-free variant then (I'm no dev, so I cannot build one myself). Feel free to keep this issue open for that purpose – or close it as answered. All the best for your project meanwhile!

**Comment by IzzySoft** [comment]
As you've closed the issue as "completed", is there a FOSS APK available somewhere now? There are no APK files at releases, and the Readme just links to Google Play.

**Comment by ohmae** [comment]
Sorry I didn't live up to your expectations. I closed this as "answered".
