### ISSUE TITLE
 Landscape and portrait sensors are reversed

### ISSUE THREAD

**Issue by Coding-Young** [ohmae/orientation-faker#9]
Hello. I am a user who is using your app usefully.

When I turn on the 'sensor rotation' while using the app on this device(SM-T536(Android 6.0.1), Perhaps the following problems arise because the device is long horizontally.), it is affected by the landscape sensor if I set the portrait sensor rotation, and the portrait sensor if I set the landscape sensor rotation. **I hope there is a 'horizontal/vertical sensor switching feature' so that 'sensor rotation' can be used correctly in all devices.** Thank you for developing this app and listening to my feedback!

+ There may be errors in English sentences because I used a translator app. I apologize for that.

**Comment by ohmae** [comment]
Thank you.
You also sent me an email. I'm sorry I couldn't reply.
I've heard that some devices do have different default orientations and sensors have different orientations. However, I don't have such a device, so it's difficult to confirm... I will consider whether there is a good way.

> I also understand very little English, so I'm writing this text using Google Translate and DeepL :wink:

**Comment by Coding-Young** [comment]
> Thank you.
> You also sent me an email. I'm sorry I couldn't reply.
> I've heard that some devices do have different default orientations and sensors have different orientations. However, I don't have such a device, so it's difficult to confirm... I will consider whether there is a good way.
> 
> > I also understand very little English, so I'm writing this text using Google Translate and DeepL :wink: 

Thank you for kind feedback!

**Comment by ohmae** [comment]
I released 4.7.5 in open beta.
For this version, I tried to implement the ability to detect devices with landscape default and adjust the orientation of the sensor.
Since I don't have such a device, could you please check if it works correctly on your device if possible?

**Comment by Coding-Young** [comment]
It works great on my device!  Thank you for accepting my feedback.
